// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUeGEFCei3k-EXOMknkxhwvNIxYiD1s-4',
    appId: '1:576991338990:web:4ff3221c0d9ef57e202eff',
    messagingSenderId: '576991338990',
    projectId: 'diario-3ee0d',
    authDomain: 'diario-3ee0d.firebaseapp.com',
    databaseURL: 'https://diario-3ee0d-default-rtdb.firebaseio.com',
    storageBucket: 'diario-3ee0d.appspot.com',
    measurementId: 'G-141P5VZM16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjxCzb-WnNGNYyOeyljYPA5XuCui_5QpY',
    appId: '1:576991338990:android:9739dbc36792fb11202eff',
    messagingSenderId: '576991338990',
    projectId: 'diario-3ee0d',
    databaseURL: 'https://diario-3ee0d-default-rtdb.firebaseio.com',
    storageBucket: 'diario-3ee0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOUN_duggK4udvNcIa2Gw97I3nLEQE32Q',
    appId: '1:576991338990:ios:b1aa7d389d670d5f202eff',
    messagingSenderId: '576991338990',
    projectId: 'diario-3ee0d',
    databaseURL: 'https://diario-3ee0d-default-rtdb.firebaseio.com',
    storageBucket: 'diario-3ee0d.appspot.com',
    androidClientId: '576991338990-9kjo0710clf4jlkjjnaoc020n0pksa84.apps.googleusercontent.com',
    iosClientId: '576991338990-oge6uubmk71dlvo77tahhcu2068ml8r2.apps.googleusercontent.com',
    iosBundleId: 'com.tecmante.diario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOUN_duggK4udvNcIa2Gw97I3nLEQE32Q',
    appId: '1:576991338990:ios:db73d5d743b216a0202eff',
    messagingSenderId: '576991338990',
    projectId: 'diario-3ee0d',
    databaseURL: 'https://diario-3ee0d-default-rtdb.firebaseio.com',
    storageBucket: 'diario-3ee0d.appspot.com',
    androidClientId: '576991338990-9kjo0710clf4jlkjjnaoc020n0pksa84.apps.googleusercontent.com',
    iosClientId: '576991338990-8njppu491njkl3qfh8iplbabdvbikm35.apps.googleusercontent.com',
    iosBundleId: 'com.tecmante.diario.RunnerTests',
  );
}
